### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by dsp-kuai** [miluoalbert/MACHIN3tools_zh-Hans#1]

**Comment by dsp-kuai** [comment]
Traceback (most recent call last):
File "F:Program Files (x86)SteamlsteamappsicommoniBlendern2 82\scriptslmodulesladdon utilspy", line 351. in enable
mod=__ import_ (module name)
ModuleNotFoundError: No module named 'MACHIN3tools, zh.Hans-0'

**Comment by puredark8light** [comment]
> Traceback (most recent call last):
> File "F:Program Files (x86)SteamlsteamappsicommoniBlendern2 82\scriptslmodulesladdon utilspy", line 351. in enable
> mod=__ import_ (module name)
> ModuleNotFoundError: No module named 'MACHIN3tools, zh.Hans-0'

by changing the name of the File folder to "MACHIN3tools, zh.Hans-0" and the value of  "name" in "_inti_.py" to "MACHIN3tools, zh.Hans-0" .  the bug could be fixed

**Comment by YLXDXX** [comment]
不同系统报错居然不一样，处理方式都差不多，我的是Manjaro，报错
```
Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'MACHIN3tools_zh-Hans-0'
```
在自己家目录下的配置文件中`/home/name/.config/blender/2.82/scripts/addons`将该插件文件夹的名字改为`MACHIN3tools_zh-Hans-0`，再进入该文件夹，将‘__init__.py’里面的‘name’后的字段改为‘MACHIN3tools_zh-Hans-0’，就可以正常使用了
